FROM python:3.11
WORKDIR /usr/src/app
COPY . .
RUN apt-get update && apt-get install -y portaudio19-dev && apt-get install -y ffmpeg
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8080
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=127.0.0.1
CMD ["flask", "run"]
